[theme]
primaryColor = "#2E8B57"           # Slightly muted Sea Green for better contrast
backgroundColor = "#000000"       # Pure black background
secondaryBackgroundColor = "#0A0A0A"  # Slightly lighter black
textColor = "#FFFFFF"             # Bright white text for clarity
font = "monospace"                # Hacker-style font for a clean Matrix vibe
