[theme]
primaryColor = "#FFD700"         # Gold color to match ✨
backgroundColor = "#111827"       # Deep navy-black
secondaryBackgroundColor = "#1F2937"  # Slightly lighter gray
textColor = "#F9FAFB"            # Off-white text
font = "Inter"                   # Modern, clean sans-serif font